/**
 * Supabase Database Types (Placeholder)
 * 
 * This file will be auto-generated by: npm run db:types
 * After running: supabase db reset
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
