/**
 * Auto-generated Supabase TypeScript types.
 *
 * DO NOT edit this file manually.
 * Regenerate with: npm run db:types
 *
 * This file is a placeholder until the first type generation run.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      merchants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: "grocery" | "water" | "gas";
          owner_user_id: string;
          is_active: boolean;
          is_open: boolean;
          address: string;
          phone: string;
          order_timeout_minutes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category: "grocery" | "water" | "gas";
          owner_user_id: string;
          is_active?: boolean;
          is_open?: boolean;
          address: string;
          phone: string;
          order_timeout_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          category?: "grocery" | "water" | "gas";
          owner_user_id?: string;
          is_active?: boolean;
          is_open?: boolean;
          address?: string;
          phone?: string;
          order_timeout_minutes?: number;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          merchant_id: string;
          name: string;
          description: string | null;
          price: number;
          unit: string;
          stock_count: number | null;
          is_available: boolean;
          image_url: string | null;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          merchant_id: string;
          name: string;
          description?: string | null;
          price: number;
          unit: string;
          stock_count?: number | null;
          is_available?: boolean;
          image_url?: string | null;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          merchant_id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          unit?: string;
          stock_count?: number | null;
          is_available?: boolean;
          image_url?: string | null;
          display_order?: number;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          full_name: string;
          phone: string;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          phone: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          phone?: string;
        };
      };
      customer_addresses: {
        Row: {
          id: string;
          customer_id: string;
          label: string;
          address_line: string;
          district: string;
          city: string;
          notes: string | null;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          label: string;
          address_line: string;
          district: string;
          city?: string;
          notes?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          label?: string;
          address_line?: string;
          district?: string;
          city?: string;
          notes?: string | null;
          is_default?: boolean;
        };
      };
      couriers: {
        Row: {
          id: string;
          merchant_id: string;
          user_id: string;
          full_name: string;
          phone: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          merchant_id: string;
          user_id: string;
          full_name: string;
          phone: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          merchant_id?: string;
          user_id?: string;
          full_name?: string;
          phone?: string;
          is_active?: boolean;
        };
      };
      orders: {
        Row: {
          id: string;
          merchant_id: string;
          customer_id: string;
          courier_id: string | null;
          status: string;
          total_amount: number;
          delivery_address: Json;
          customer_notes: string | null;
          merchant_notes: string | null;
          rejection_reason: string | null;
          failure_reason: string | null;
          created_at: string;
          accepted_at: string | null;
          ready_at: string | null;
          assigned_at: string | null;
          picked_up_at: string | null;
          delivered_at: string | null;
        };
        Insert: {
          id?: string;
          merchant_id: string;
          customer_id: string;
          courier_id?: string | null;
          status?: string;
          total_amount: number;
          delivery_address: Json;
          customer_notes?: string | null;
          merchant_notes?: string | null;
          rejection_reason?: string | null;
          failure_reason?: string | null;
          created_at?: string;
          accepted_at?: string | null;
          ready_at?: string | null;
          assigned_at?: string | null;
          picked_up_at?: string | null;
          delivered_at?: string | null;
        };
        Update: {
          id?: string;
          courier_id?: string | null;
          status?: string;
          merchant_notes?: string | null;
          rejection_reason?: string | null;
          failure_reason?: string | null;
          accepted_at?: string | null;
          ready_at?: string | null;
          assigned_at?: string | null;
          picked_up_at?: string | null;
          delivered_at?: string | null;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          product_name: string;
          unit_price: number;
          quantity: number;
          line_total: number;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          product_name: string;
          unit_price: number;
          quantity: number;
          line_total: number;
        };
        Update: Record<string, never>;
      };
      order_status_log: {
        Row: {
          id: string;
          order_id: string;
          from_status: string | null;
          to_status: string;
          actor_id: string;
          actor_role: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          from_status?: string | null;
          to_status: string;
          actor_id: string;
          actor_role: string;
          note?: string | null;
          created_at?: string;
        };
        Update: Record<string, never>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
