/**
 * Supabase Database Types
 *
 * Auto-generated by: npm run db:types (after supabase db reset)
 * Hand-written interim schema matching migrations 00001–00014.
 * Replace this file entirely after running: supabase link && supabase db pull
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type OrderStatus =
  | "PENDING"
  | "CONFIRMED"
  | "READY"
  | "ASSIGNED"
  | "IN_TRANSIT"
  | "DELIVERED"
  | "REJECTED"
  | "FAILED_DELIVERY"
  | "CANCELLED";

export interface Database {
  public: {
    Tables: {
      merchants: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          logo_url: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          is_active: boolean;
          is_open: boolean;
          minimum_order_amount: number | null;
          average_delivery_minutes: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["merchants"]["Row"]> & {
          name: string;
          slug: string;
        };
        Update: Partial<Database["public"]["Tables"]["merchants"]["Row"]>;
      };
      products: {
        Row: {
          id: string;
          merchant_id: string;
          name: string;
          description: string | null;
          price: number;
          image_url: string | null;
          category: string | null;
          is_available: boolean;
          sort_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["products"]["Row"]> & {
          merchant_id: string;
          name: string;
          price: number;
        };
        Update: Partial<Database["public"]["Tables"]["products"]["Row"]>;
      };
      customers: {
        Row: {
          id: string;
          user_id: string;
          full_name: string | null;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["customers"]["Row"]> & {
          user_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["customers"]["Row"]>;
      };
      customer_addresses: {
        Row: {
          id: string;
          customer_id: string;
          label: string | null;
          full_address: string;
          district: string;
          latitude: number | null;
          longitude: number | null;
          is_default: boolean | null;
          created_at: string;
        };
        Insert: Partial<
          Database["public"]["Tables"]["customer_addresses"]["Row"]
        > & {
          customer_id: string;
          full_address: string;
          district: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["customer_addresses"]["Row"]
        >;
      };
      couriers: {
        Row: {
          id: string;
          user_id: string;
          full_name: string | null;
          phone: string | null;
          vehicle_type: string | null;
          is_active: boolean;
          is_available: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["couriers"]["Row"]> & {
          user_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["couriers"]["Row"]>;
      };
      orders: {
        Row: {
          id: string;
          customer_id: string;
          merchant_id: string;
          courier_id: string | null;
          status: OrderStatus;
          total_amount: number;
          delivery_address: Json;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["orders"]["Row"]> & {
          customer_id: string;
          merchant_id: string;
          status: OrderStatus;
          total_amount: number;
          delivery_address: Json;
        };
        Update: Partial<Database["public"]["Tables"]["orders"]["Row"]>;
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          snapshot: Json | null;
          created_at: string;
        };
        Insert: Partial<
          Database["public"]["Tables"]["order_items"]["Row"]
        > & {
          order_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          total_price: number;
        };
        Update: Partial<Database["public"]["Tables"]["order_items"]["Row"]>;
      };
      order_status_log: {
        Row: {
          id: string;
          order_id: string;
          status: OrderStatus;
          actor_role: string | null;
          actor_id: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: Partial<
          Database["public"]["Tables"]["order_status_log"]["Row"]
        > & {
          order_id: string;
          status: OrderStatus;
        };
        Update: never;
      };
      cron_lock: {
        Row: {
          job_name: string;
          last_run_at: string;
          last_run_by: string | null;
          last_cancelled: number;
          last_scanned: number;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["cron_lock"]["Row"]> & {
          job_name: string;
        };
        Update: Partial<Database["public"]["Tables"]["cron_lock"]["Row"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      order_status: OrderStatus;
    };
  };
}
